require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbilitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Ability. As you add validations to Ability, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbilitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all abilities as @abilities" do
      ability = Ability.create! valid_attributes
      get :index, {}, valid_session
      assigns(:abilities).should eq([ability])
    end
  end

  describe "GET show" do
    it "assigns the requested ability as @ability" do
      ability = Ability.create! valid_attributes
      get :show, {:id => ability.to_param}, valid_session
      assigns(:ability).should eq(ability)
    end
  end

  describe "GET new" do
    it "assigns a new ability as @ability" do
      get :new, {}, valid_session
      assigns(:ability).should be_a_new(Ability)
    end
  end

  describe "GET edit" do
    it "assigns the requested ability as @ability" do
      ability = Ability.create! valid_attributes
      get :edit, {:id => ability.to_param}, valid_session
      assigns(:ability).should eq(ability)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ability" do
        expect {
          post :create, {:ability => valid_attributes}, valid_session
        }.to change(Ability, :count).by(1)
      end

      it "assigns a newly created ability as @ability" do
        post :create, {:ability => valid_attributes}, valid_session
        assigns(:ability).should be_a(Ability)
        assigns(:ability).should be_persisted
      end

      it "redirects to the created ability" do
        post :create, {:ability => valid_attributes}, valid_session
        response.should redirect_to(Ability.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ability as @ability" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ability.any_instance.stub(:save).and_return(false)
        post :create, {:ability => { "name" => "invalid value" }}, valid_session
        assigns(:ability).should be_a_new(Ability)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ability.any_instance.stub(:save).and_return(false)
        post :create, {:ability => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ability" do
        ability = Ability.create! valid_attributes
        # Assuming there are no other abilities in the database, this
        # specifies that the Ability created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ability.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => ability.to_param, :ability => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested ability as @ability" do
        ability = Ability.create! valid_attributes
        put :update, {:id => ability.to_param, :ability => valid_attributes}, valid_session
        assigns(:ability).should eq(ability)
      end

      it "redirects to the ability" do
        ability = Ability.create! valid_attributes
        put :update, {:id => ability.to_param, :ability => valid_attributes}, valid_session
        response.should redirect_to(ability)
      end
    end

    describe "with invalid params" do
      it "assigns the ability as @ability" do
        ability = Ability.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ability.any_instance.stub(:save).and_return(false)
        put :update, {:id => ability.to_param, :ability => { "name" => "invalid value" }}, valid_session
        assigns(:ability).should eq(ability)
      end

      it "re-renders the 'edit' template" do
        ability = Ability.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ability.any_instance.stub(:save).and_return(false)
        put :update, {:id => ability.to_param, :ability => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ability" do
      ability = Ability.create! valid_attributes
      expect {
        delete :destroy, {:id => ability.to_param}, valid_session
      }.to change(Ability, :count).by(-1)
    end

    it "redirects to the abilities list" do
      ability = Ability.create! valid_attributes
      delete :destroy, {:id => ability.to_param}, valid_session
      response.should redirect_to(abilities_url)
    end
  end

end
